name: build
on: [push]
jobs:
  build_job: # job name
    runs-on: ubuntu-22.04
    steps:
      - name: Use JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Standard Checkout
        uses: actions/checkout@v3.2.0

      - name: Build with Maven
        run: mvn -B verify

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v3.1.1
        with:
          name: jacoco-report
          path: microf-custom/target/site/jacoco-aggregate/

  generate_badges:
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
    needs: build_job
    steps:
      - name: Get JaCoCo coverage report
        uses: actions/download-artifact@v3.0.2
        with:
          name: jacoco-report
          path: microf-custom/target/site/jacoco-aggregate/

      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2.9.0
        with:
          jacoco-csv-file: microf-custom/target/site/jacoco-aggregate/jacoco.csv
          generate-branches-badge: true

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: Shallow Checkout
        uses: actions/checkout@v3.2.0
        with:
          fetch-depth: 1

      - name: Commit and push the badge (if it changed)
        uses: EndBug/add-and-commit@v9.1.1
        with:
          default_author: github_actions
          message: 'Autogenerated JaCoCo coverage badge'
          add: '*.svg'