name: build
on: [push]
jobs:
  build_job: # job name
    runs-on: ubuntu-22.04
    steps:
      # because Avispa ECM is not available now in any public Maven repository
      # it needs to be checked out and installed manually
      - name: Checkout of Avispa ECM
        uses: actions/checkout@v3.2.0
        with:
          repository: RHarryH/avispa-ecm

      - name: Installment of Avispa ECM into Maven repository
        run: mvn -B -DskipTests install

      # here the actual build starts
      - name: Standard Checkout
        uses: actions/checkout@v3.2.0

      - name: Build with Maven
        run: mvn -B verify

      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2.9.0
        with:
          jacoco-csv-file: microf-custom/target/site/jacoco-aggregate/jacoco.csv
          generate-branches-badge: true

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: Commit and push the badge (if it changed)
        uses: EndBug/add-and-commit@v9.1.1
        with:
          default_author: github_actions
          message: 'Autogenerated JaCoCo coverage badge'
          add: '*.svg'

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v3.1.1
        with:
          name: jacoco-report
          path: target/site/jacoco/